spring:
  profiles:
    active: prod
business:
  payImageHost: http://localhost:8088/uploadpic/


product:
  ImageHost: http://img.cdn.imbession.top/

logging:
  config: classpath:logback-spring.xml
  level:
    dao: debug
    org:
      mybatis: debug
#关闭订单时间
order:
  close:
    tiomeout: 1
