#本地环境
business:
  payImageHost: http://localhost:8088/uploadpic/


product:
  ImageHost: http://img.cdn.imbession.top/
server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      max-active: 20
      max-wait: 6000
      min-idle: 1
      test-on-borrow: true
      test-on-return: true
      username: root
      password: root
      url: jdbc:mysql://localhost:3308/shopping?characterEncoding=utf8&serverTimezone=Asia/Shanghai
  thymeleaf:
    mode: HTML5
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB


mybatis:
  mapper-locations: classpath*:mappers/*Mapper.xml
  config-location: classpath:mybatis-cofig.xml

#分页插件配置
pagehelper:
  auto-dialect: maysql
  reasonable: true
  support-methods-arguments: true
  params: countSql
  #配置SQL语句打印
logging:
  level:
    com.edu.dao: debug
#配置redis链接参数
redis:
  max:
    total: 8
    idle: 8
  min:
    idle: 2
  test:
    borrow: true
    return: true
  ip: 121.36.13.233
  port: 5379
  password: quwosulilei521@
  timeout: 2000

